package type1

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"
)

// dumpFontDescriptor creates a go source file containing
// the description of the fonts `fs`
// WinAnsi is used instead of Standard because more western
// usual characters are supported
func dumpFontDescriptor(fs []Font) error {
	var code strings.Builder
	code.WriteString("package standardfonts\n")
	code.WriteString("// Code generated by standardfonts/generate. DO NOT EDIT\n\n")

	var sumupMap strings.Builder

	sumupMap.WriteString("// Fonts is a convenient mapping from a font name to its descriptor.\n")
	sumupMap.WriteString("var Fonts = map[string]Metrics{\n")

	for _, f := range fs {
		fontDesc := f.FontDescriptor()
		all := f.simplifiedMetrics()
		goFontName := strings.ReplaceAll(string(fontDesc.FontName), "-", "_")
		code.WriteString("var " + goFontName + " = Metrics{\n")
		code.WriteString(fmt.Sprintf("Descriptor: %#v,\n", fontDesc))
		code.WriteString(fmt.Sprintf("Builtin: %#v,\n", f.charCodeToCharName))
		code.WriteString(fmt.Sprintf("// %d characters\n", len(all)))
		code.WriteString(fmt.Sprintf("CharsWidths: %#v,\n", all))
		code.WriteString("}\n")

		sumupMap.WriteString(fmt.Sprintf(" %q: %s,\n", string(fontDesc.FontName), goFontName))
	}
	sumupMap.WriteString("}")

	code.WriteString("\n" + sumupMap.String())

	filename := "../fonts.go"
	err := ioutil.WriteFile(filename, []byte(code.String()), os.ModePerm)
	if err != nil {
		return err
	}

	err = exec.Command("goimports", "-w", filename).Run()
	return err
}
